import { Theme } from "../types";

export const THEMES: Theme[] = [
	{
		id: "witnesses",
		name: "Witnesses",
		logoType: "light",
		backgroundImage: "/assets/images/witnesses.png",
		backgroundColour: "#DF6140",
		primaryForeground: "#10297D",
		primaryBackground: "#ffffff",
		secondaryForeground: "#ffffff",
		secondaryBackground: "#10297D",
		titleColor: "#ffffff",
		paddingTop: 75,
		paddingLeft: 0,
		paddingRight: 0,
		paddingBottom: 0
	},
	{
		id: "amigos-and-agape",
		name: "Amigos and Agape",
		logoType: "light",
		backgroundImage: "/assets/images/amigos-and-agape.png",
		backgroundColour: "#0767db",
		primaryForeground: "#ffffff",
		primaryBackground: "#FD3F40",
		secondaryForeground: "#ffffff",
		secondaryBackground: "#0767db",
		titleColor: "#FD3F40",
		paddingTop: 0,
		paddingLeft: 0,
		paddingRight: 0,
		paddingBottom: 0
	},
	{
		id: "vision-sunday",
		name: "Vision Sun",
		logoType: "light",
		backgroundImage: "/assets/images/vision-sunday.png",
		backgroundColour: "#FD0003",
		primaryForeground: "#FEF293",
		primaryBackground: "#FD0003",
		secondaryForeground: "#FD0003",
		secondaryBackground: "#FFFFFF",
		titleColor: "#ffffff",
		paddingTop: 25,
		paddingLeft: 0,
		paddingRight: 0,
		paddingBottom: 0
	},
	{
		id: "ttots",
		name: "The Things of the Spirit",
		logoType: "light",
		backgroundImage: "/assets/images/ttots.png",
		backgroundColour: "#011278",
		primaryForeground: "#011278",
		primaryBackground: "#ffffff",
		secondaryForeground: "#941436",
		secondaryBackground: "#FFE80B",
		titleColor: "#ffffff",
		paddingTop: 75,
		paddingLeft: 0,
		paddingRight: 0,
		paddingBottom: 0
	},
	{
		id: "nytgs",
		name: "New Year Thanksgiving Service",
		logoType: "light",
		backgroundImage: "/assets/images/nytgs.png",
		backgroundColour: "#011278",
		primaryForeground: "#011278",
		primaryBackground: "#ffffff",
		secondaryForeground: "#ffffff",
		secondaryBackground: "#c92e12",
		titleColor: "#ffffff",
		paddingTop: 75,
		paddingLeft: 0,
		paddingRight: 0,
		paddingBottom: 0
	},
	{
		id: "eoy",
		name: "EOY Mega Service",
		logoType: "light",
		backgroundImage: "/assets/images/eoy.png",
		backgroundColour: "#011278",
		primaryForeground: "#011278",
		primaryBackground: "#ffffff",
		secondaryForeground: "#ffffff",
		secondaryBackground: "#c92e12",
		titleColor: "#ffffff",
		paddingTop: 75,
		paddingLeft: 0,
		paddingRight: 0,
		paddingBottom: 0
	},
	{
		id: "grace-radiance",
		name: "Grace & Radiance",
		logoType: "dark",
		backgroundImage: "/assets/images/grace-and-radiance.png",
		backgroundColour: "#fdfcfb",
		primaryForeground: "#1e7e34",
		primaryBackground: "#ffffff",
		secondaryForeground: "#ffffff",
		secondaryBackground: "#333333",
		titleColor: "#333333",
		paddingTop: 75,
		paddingLeft: 0,
		paddingRight: 0,
		paddingBottom: 0
	},
	{
		id: "faith-an-divine-guidance",
		name: "Faith & Divine Guidance",
		logoType: "light",
		backgroundImage: "/assets/images/faith-and-divine-guidance.png",
		backgroundColour: "#011347",
		primaryForeground: "#011347",
		primaryBackground: "#ffffff",
		secondaryForeground: "#ffffff",
		secondaryBackground: "#E7731A",
		titleColor: "#ffffff",
		paddingTop: 75,
		paddingLeft: 0,
		paddingRight: 0,
		paddingBottom: 0
	},
	{
		id: "royal-purple",
		name: "Royal Purple",
		logoType: "light",
		backgroundImage: "/assets/images/royal-purple.jpg",
		backgroundColour: "#2d1b4e",
		primaryForeground: "#ffffff",
		primaryBackground: "#6b46c1",
		secondaryForeground: "#6b46c1",
		secondaryBackground: "#faf5ff",
		titleColor: "#faf5ff",
		paddingTop: 75,
		paddingLeft: 0,
		paddingRight: 0,
		paddingBottom: 0
	},
	{
		id: "autumn-blessing",
		name: "Autumn Blessing",
		logoType: "dark",
		backgroundImage: "/assets/images/autumn-blessing.jpg",
		backgroundColour: "#fff7ed",
		primaryForeground: "#7c2d12",
		primaryBackground: "#fed7aa",
		secondaryForeground: "#7c2d12",
		secondaryBackground: "#ffffff",
		titleColor: "#7c2d12",
		paddingTop: 75,
		paddingLeft: 0,
		paddingRight: 0,
		paddingBottom: 0
	},
	{
		id: "ocean-calm",
		name: "Ocean Calm",
		logoType: "light",
		backgroundImage: "/assets/images/ocean-calm.jpg",
		backgroundColour: "#0c4a6e",
		primaryForeground: "#ffffff",
		primaryBackground: "#0891b2",
		secondaryForeground: "#0891b2",
		secondaryBackground: "#ffffff",
		titleColor: "#ffffff",
		paddingTop: 75,
		paddingLeft: 0,
		paddingRight: 0,
		paddingBottom: 0
	},
	{
		id: "spring-hope",
		name: "Spring Hope",
		logoType: "dark",
		backgroundImage: "/assets/images/spring-hope.jpg",
		backgroundColour: "#ecfdf5",
		primaryForeground: "#065f46",
		primaryBackground: "#a7f3d0",
		secondaryForeground: "#065f46",
		secondaryBackground: "#ffffff",
		titleColor: "#065f46",
		paddingTop: 75,
		paddingLeft: 0,
		paddingRight: 0,
		paddingBottom: 0
	}
];

export const DEFAULT_THEME = THEMES[0];
